# fly.toml app configuration file generated for frpntust on 2023-12-19T08:15:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frpntust"
primary_region = "sin"
kill_signal = "SIGTERM"
kill_timeout = "2m0s"

# frp control plane
# frp HTTP server (for dashboard or HTTP tunnel)
[http_service]
  internal_port = 8080
  force_https = true
  [http_service.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

# [[services]]
#   protocol = "udp"
#   internal_port = 7000

#   [[services.ports]]
#     port = 7000
#   [services.concurrency]
#     type = "connections"
#     hard_limit = 25
#     soft_limit = 20

# [[services]]
#   protocol = "udp"
#   internal_port = 7001

#   [[services.ports]]
#     port = 7001
#   [services.concurrency]
#     type = "connections"
#     hard_limit = 25
#     soft_limit = 20

# frp TCP server
[[services]]
 protocol = "tcp"
 internal_port = 7000

 [[services.ports]]
   port = 7000
 [services.concurrency]
   type = "connections"
   hard_limit = 25
   soft_limit = 20
   
[[services]]
  protocol = "tcp"
  internal_port = 25565

  [[services.ports]]
    port = 25565
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
