


bindPort = 7000

# frp dashboard
webServer.addr = "::"
webServer.port = 8080
webServer.user = "admin"
webServer.password = "{{ .Envs.FRP_DASHBOARD_PWD }}"

# Data plane binding
# For TCP tunnels, set to 0.0.0.0 (or :: in IPv6)
# For UDP tunnels, set to fly-global-services
# proxyBindAddr = "0.0.0.0"

# frp authentication
auth.method = "token"
auth.token = "{{ .Envs.FRP_TOKEN }}"
